### Imports

In [1]:
import os
import glob
import pandas as pd
import numpy as np
import scipy.stats as st

from IPython.display import display

### Opening Dataset

In [2]:
os.chdir(".")
df = pd.read_csv("../dataset/madrid_immo.csv")
display(df)

,url,address,loc,price,m2,type
0,https://pisos.com/en/comprar/casa-puente_de_va...,"calle de mejorana, near calle del conde rodríg...",Entrevías,128000,76.0,house
1,https://pisos.com/en/comprar/chalet_adosado-ch...,hispanoamerica,Hispanoamérica,990000,287.0,house
2,https://pisos.com/en/comprar/chalet-nino_jesus...,niño jesús,Niño Jesús,1318000,263.0,house
3,https://pisos.com/en/comprar/chalet-puente_de_...,"calle de membezar, near calle de la campiña",Entrevías,139000,69.0,house
4,https://pisos.com/en/comprar/chalet-chamartin_...,chamartin,Hispanoamérica,1390000,370.0,house
...,...,...,...,...,...,...
30060,http://english.habitaclia.com/buy-house-cerro_...,NaN,El Cañaveral-Los Berrocales,345000,200.0,house
30061,http://english.habitaclia.com/buy-semi_detache...,NaN,San Isidro,450000,250.0,house
30062,http://english.habitaclia.com/buy-semi_detache...,NaN,San Diego,89000,38.0,house
30063,http://english.habitaclia.com/buy-semi_detache...,NaN,Rejas,670000,340.0,house
30064,http://english.habitaclia.com/buy-house-penagr...,NaN,Peñagrande,1250000,519.0,house

### Filtering all locations

In [3]:
unique_locs = df['loc'].unique()
len(unique_locs)
unique_locs

array(['Entrevías', 'Hispanoamérica', 'Niño Jesús', 'Rosas',
       'Nueva España', 'Castilla', 'Casco Histórico de Barajas',
       'Mirasierra-Arroyo del Fresno', 'Piovera', 'Ciudad Universitaria',
       'Quintana', 'Canillas', 'Simancas', 'Valverde', 'Puerta del Ángel',
       'El Viso', 'San Isidro', 'Cármenes', 'Guindalera', 'Numancia',
       'Bellas Vistas', 'Prosperidad', 'Vista Alegre', 'El Cañaveral',
       'Peñagrande', 'Corralejos', 'Valdemarín', 'San Diego',
       'Cuatro Caminos', 'Salvador', 'Fuente del Berro', 'Canillejas',
       'Aravaca', 'El Plantío', 'Fuentelarreina', 'El Pardo', 'Timón',
       'Valdebebas-Valdefuentes', 'Madrid Capital', 'Rejas', 'Berruguete',
       'Aeropuerto', 'Palomas', 'Ciudad Jardín', 'Embajadores-Lavapiés',
       'Portazgo', 'Valdeacederas', 'Alameda de Osuna', 'Valdezarza',
       'San Fermín', 'La Paz', 'Lista', 'Jerónimos', 'Hellín',
       'Centro Histórico', 'Orcasitas', 'Ambroz', 'Castellana',
       'Concepción', 'Apóstol Santiago', 'Zofío', 'Los Rosales',
       'Atalaya', 'Campamento', 'Casco Histórico de Vallecas',
       'Ensanche de Vallecas-Valdecarros', 'Palacio', 'Montecarmelo',
       'Pradolongo', 'Colina', 'Las Águilas', 'San Andrés', 'Comillas',
       'Almenara', 'Aluche', 'Abrantes', 'Moscardó', 'Palos de Moguer',
       'Opañel', 'Argüelles', 'Delicias', 'Pueblo Nuevo', 'Legazpi',
       'Amposta', 'Chopera', 'Palomeras Bajas', 'Palomeras Sureste',
       'Almagro', 'Sanchinarro', 'Pacífico', 'Las Tablas', 'Goya',
       'Gaztambide', 'Universidad-Malasaña', 'Sol', 'Cortes-Huertas',
       'Ventas', 'Pau de Carabanchel', 'Ibiza', 'Trafalgar', 'Orcasur',
       'Recoletos', 'Justicia-Chueca', 'Casa de Campo', 'Butarque',
       'Marroquina', 'Buenavista', 'Vinateros', 'Acacias', 'Imperial',
       'Castillejos', 'Ríos Rosas', 'Pinar del Rey', 'Fontarrón',
       'Puerta Bonita', 'Costillares', 'Los Ángeles', 'Lucero',
       'Valderrivas', 'Almendrales', 'Estrella', 'Arcos', 'Santa Eugenia',
       'Media Legua', 'Pavones', 'Pilar', 'Adelfas', 'San Pascual',
       'San Juan Bautista', 'Vallehermoso', 'Arapiles', 'San Cristóbal',
       'Atocha', 'Virgen del Cortijo-Manoteras', 'Moncloa-Aravaca',
       'Valdebernardo', 'Cuatro Vientos', 'Embajadores',
       'Universidad, Malasaña', 'Puerta del Ángel, Puerta del Ángel',
       'Jerónimos, Pradolongo', 'Los Ángeles, Los Ángeles',
       'Ríos Rosas-Nuevos Ministerios', 'Tres Olivos-Valverde',
       'Castillejos-Cuzco', 'Ciudad Lineal', 'Concepción, Concepción',
       'Castellana, Centro Histórico', 'San Andrés, San Andrés',
       'Barajas, Casco Histórico de Barajas', 'Pacífico, Pacífico',
       'Ríos Rosas, Ríos Rosas', 'Entrevías, Entrevías',
       'Embajadores, Embajadores-Lavapiés', 'San Diego, Palomeras Bajas',
       'Hispanoamérica, Hispanoamérica', 'Cortes, Cortes-Huertas',
       'Universidad, Universidad-Malasaña',
       'San Cristobal, San Cristóbal', 'Opañel, Opañel',
       'Las Águilas, Las Águilas', 'Moscardó, Moscardó',
       'Argüelles, Argüelles', 'El Viso, Almenara', 'Timón, Timón',
       'Pacífico, Casco Histórico de Vallecas', 'Goya, Recoletos',
       'Justicia, Justicia-Chueca', 'Pueblo Nuevo, Castilla',
       'Jerónimos, Moscardó', 'Pilar, Fuentelarreina',
       'Jerónimos, Comillas', 'Peñagrande, Peñagrande',
       'Virgen del Cortijo, Virgen del Cortijo-Manoteras',
       'San Fermín, San Fermín', 'Nueva España, Nueva España',
       'Miguel Hernandez, Orcasur', 'Trafalgar, Justicia-Chueca',
       'Valdecarros, Ensanche de Vallecas-Valdecarros',
       'Ciudad Jardín, Almagro', 'Jerónimos, Puerta Bonita',
       'Salamanca, Gaztambide', 'Zofio, Zofío', 'Fontarrón, Fontarrón',
       'Miguel Hernandez, San Diego', 'Ciudad Jardín, Ciudad Jardín',
       'Mirasierra, Mirasierra-Arroyo del Fresno',
       'Castellana, Valderrivas', 'Niño Jesús, Niño Jesús',
       'Castillejos, Peñagrande', 'Universidad', 'Latina',
       'Jerónimos, San Isidro', 'Trafalgar, Bellas Vistas',
       'Apóstol Santiago, Apóstol Santiago',
       'Carabanchel, Pau de Carabanchel', 'Recoletos, Comillas',
       'Recoletos, Palacio', 'Buenavista, Pau de Carabanchel',
       'Ventas, Fuente del Berro',
       'El Cañaveral - Los Berrocales, El Cañaveral',
       'Jerónimos, Casa de Campo', 'Jerónimos, Orcasur',
       'Recoletos, Cármenes', 'Rosas, Pueblo Nuevo', 'Zofio',
       'Valdebebas, Valdebebas-Valdefuentes', 'Miguel Hernandez',
       'Chamberí', 'Arganzuela', 'Valdebebas, VALDEBEBAS UNICO',
       'Rosas, Palomas', 'San Juan', 'Chamartín', 'Carabanchel',
       'Villa de Vallecas', 'La Paz, Calle Julio Palacios 29-31',
       'Vicálvaro', 'Puente de Vallecas', 'Jerónimos, Primitiva Gañan',
       'Valdefuentes', 'San Diego, Collado De Las Vertientes',
       'Salamanca', 'Jerónimos, Cármenes', 'Tetuán', 'Justicia',
       'Jerónimos, Padre Amigo', 'San Juán Bautista',
       'Miguel Hernandez, Gonzalez Soto', 'Castillejos, Molina',
       'Ensanche de Vallecas', 'Palomeras Bajas, Hispanoamérica',
       'El Plantío, El Plantío', 'Los Cármenes, Los Cármenes',
       'Jerónimos, Jerónimos', 'Cortes',
       'Santa Eugenia, Casco Histórico de Vallecas', 'Hellín, Hellín',
       'Valdemarín, Valdemarín', 'Jerónimos, Buenavista', 'San Blas',
       'Ciudad Jardín, Chopera', 'Chamberí, Recoletos', 'Hortaleza',
       'Retiro', 'Valdecarros', 'Horcajo, Estrella',
       'Trafalgar, Berruguete', 'Villaverde', 'Casco Histórico Vicálvaro',
       'Valderribas', 'Concepción, Urbanizacion Guadalupe',
       'Miguel Hernandez, Palomeras Bajas', 'Jerónimos, Imperial',
       'Puerta de Hierro', 'Mirasierra', 'Carabanchel, Pilar',
       'Trafalgar, Embajadores-Lavapiés', 'El Goloso', 'Usera',
       'Salamanca, Arapiles', 'Trafalgar, Cortes-Huertas', 'Madrid-Sur',
       'Trafalgar, Recoletos', 'Zona Industrial Vicálvaro, El Cañaveral',
       'Barrio del Pilar', 'Pacífico, Los Berrocales',
       'El Goloso, Mirasierra-Arroyo del Fresno', 'Arganzuela, Madrid',
       'Carabanchel, Numancia', 'Barajas, Los Coronales',
       'Horcajo, Ventas', 'Jerónimos, Pacífico', 'Palomas, Piovera',
       'El Viso, Valverde', 'Salamanca, Magán',
       'Cuatro Caminos, Almenara', 'El Goloso, El Pardo',
       'Chamberí, Castellana', 'Cortes, Ensanche de Vallecas-La Gavia',
       'Valdemarín, Ciudad Universitaria', 'Valdeacederas, SORGO 14',
       'Arturo Soria', 'Horcajo', 'Arganzuela, JUNTO PUERTA DE TOLEDO',
       'Palomas, Palomeras Bajas', 'San Juán Bautista, San Juan Bautista',
       'Valdefuentes, Valdebebas-Valdefuentes', 'San Cristobal',
       'Hortaleza, Ensanche', 'Jerónimos, Tranquilo',
       'Carabanchel, Castilla', 'Salamanca, Universidad-Malasaña',
       'El Goloso, Madrid ,Fuencarral',
       'Justicia, Bueno y tranquilo. Agua incl. en comunidad.',
       'Comillas, Carabanchel', 'Chamberí, Niño Jesús', 'Los Cármenes',
       'Nueva Numancia, AMUEBLADO   CON TRASTERO INCLUIDO PARA ENTRAR EN VIVIR',
       'Recoletos, Arapiles', 'Goya, Atocha', 'San Diego, Adelfas',
       'El Viso, Almagro', 'Trafalgar, Gaztambide',
       'Recoletos, Nueva España', 'Recoletos, Aluche',
       'Acacias, Imperial', 'Recoletos, San Isidro',
       'El Cañaveral - Los Berrocales', 'Casco Histórico de Vicálvaro',
       'Piovera-Conde de Orgaz', 'Buena Vista', 'Valdefuentes-Valdebebas',
       'Ensanche de Vallecas-La Gavia',
       'Corralejos-Campo de las Naciones', 'Hispanoamérica-Bernabéu',
       'Orcasur-12 de Octubre', 'Ventas, Atalaya', 'Goya, Delicias',
       'Goya, San Pascual', 'Almenara-Ventilla',
       'Valdebernardo-Valderribas', 'Nueva Numancia', 'Chamberí, Arcos',
       'Pacífico, Ambroz', 'El Cañaveral-Los Berrocales',
       'Jerónimos, Fuente del Berro', 'San Andrés, San Fermín',
       'Castellana, Arcos', 'Alto del Arenal', 'San Isidro, xxxx',
       'San Pascual, Esquina a calle Torrelaguna',
       'Arapiles, Conde Duque-San Bernardo',
       'Los Ángeles, colonia del ahorro', 'Arroyo del Fresno',
       'Jerónimos, Abrantes', 'Trafalgar, Almagro',
       'Jerónimos, Las Águilas', 'Pacífico, Hellín',
       'Recoletos, Estrella', 'Covibar-Pablo Iglesias', 'Jerónimos, Sol',
       'Buenavista, Cuatro Vientos', 'El Viso, Cuatro Caminos',
       'Universidad, Sol', 'Jerónimos, Acacias', 'Embajadores, Delicias',
       'Tetuán, Madrid', 'Ciudad Jardín, Lista', 'Gaztambide, Galaxia',
       'Valdemarín, Casa Quemada', 'Valdebebas',
       'Aeropuerto, Urb. Mas Nou', 'Palomas, Rejas',
       'Valdebebas, URBANIZACION VALDEBEBAS',
       'Cuatro Caminos, Apóstol Santiago', 'Nueva España, Plaza de cuzco',
       'Castellana, Rosas', 'Canillejas, COLONIA ALFONSOXII',
       'Valdezarza, DEHESA DE LA VILLA PUERTA DE HIERRO',
       'Montecillo-Pinar de las Rozas', 'Concepción, Hispanoamérica',
       'Latina, ECUADOR -MITAD DEL  MUNDO - ECUADOR -  SURAMERICA',
       'Trafalgar, Valdemarín', 'Estremera', 'El Viso, Chamartín', nan],
      dtype=object)

### Filtering NaN locations

In [4]:
df_filtered = df[df['loc'].notnull()]

Some values appear in double (like "Valdemarin" and "Valdemarin, Valdemarin", etc.) and must be filtered first.

In [5]:
df_filtered['loc'].unique()

array(['Entrevías', 'Hispanoamérica', 'Niño Jesús', 'Rosas',
       'Nueva España', 'Castilla', 'Casco Histórico de Barajas',
       'Mirasierra-Arroyo del Fresno', 'Piovera', 'Ciudad Universitaria',
       'Quintana', 'Canillas', 'Simancas', 'Valverde', 'Puerta del Ángel',
       'El Viso', 'San Isidro', 'Cármenes', 'Guindalera', 'Numancia',
       'Bellas Vistas', 'Prosperidad', 'Vista Alegre', 'El Cañaveral',
       'Peñagrande', 'Corralejos', 'Valdemarín', 'San Diego',
       'Cuatro Caminos', 'Salvador', 'Fuente del Berro', 'Canillejas',
       'Aravaca', 'El Plantío', 'Fuentelarreina', 'El Pardo', 'Timón',
       'Valdebebas-Valdefuentes', 'Madrid Capital', 'Rejas', 'Berruguete',
       'Aeropuerto', 'Palomas', 'Ciudad Jardín', 'Embajadores-Lavapiés',
       'Portazgo', 'Valdeacederas', 'Alameda de Osuna', 'Valdezarza',
       'San Fermín', 'La Paz', 'Lista', 'Jerónimos', 'Hellín',
       'Centro Histórico', 'Orcasitas', 'Ambroz', 'Castellana',
       'Concepción', 'Apóstol Santiago', 'Zofío', 'Los Rosales',
       'Atalaya', 'Campamento', 'Casco Histórico de Vallecas',
       'Ensanche de Vallecas-Valdecarros', 'Palacio', 'Montecarmelo',
       'Pradolongo', 'Colina', 'Las Águilas', 'San Andrés', 'Comillas',
       'Almenara', 'Aluche', 'Abrantes', 'Moscardó', 'Palos de Moguer',
       'Opañel', 'Argüelles', 'Delicias', 'Pueblo Nuevo', 'Legazpi',
       'Amposta', 'Chopera', 'Palomeras Bajas', 'Palomeras Sureste',
       'Almagro', 'Sanchinarro', 'Pacífico', 'Las Tablas', 'Goya',
       'Gaztambide', 'Universidad-Malasaña', 'Sol', 'Cortes-Huertas',
       'Ventas', 'Pau de Carabanchel', 'Ibiza', 'Trafalgar', 'Orcasur',
       'Recoletos', 'Justicia-Chueca', 'Casa de Campo', 'Butarque',
       'Marroquina', 'Buenavista', 'Vinateros', 'Acacias', 'Imperial',
       'Castillejos', 'Ríos Rosas', 'Pinar del Rey', 'Fontarrón',
       'Puerta Bonita', 'Costillares', 'Los Ángeles', 'Lucero',
       'Valderrivas', 'Almendrales', 'Estrella', 'Arcos', 'Santa Eugenia',
       'Media Legua', 'Pavones', 'Pilar', 'Adelfas', 'San Pascual',
       'San Juan Bautista', 'Vallehermoso', 'Arapiles', 'San Cristóbal',
       'Atocha', 'Virgen del Cortijo-Manoteras', 'Moncloa-Aravaca',
       'Valdebernardo', 'Cuatro Vientos', 'Embajadores',
       'Universidad, Malasaña', 'Puerta del Ángel, Puerta del Ángel',
       'Jerónimos, Pradolongo', 'Los Ángeles, Los Ángeles',
       'Ríos Rosas-Nuevos Ministerios', 'Tres Olivos-Valverde',
       'Castillejos-Cuzco', 'Ciudad Lineal', 'Concepción, Concepción',
       'Castellana, Centro Histórico', 'San Andrés, San Andrés',
       'Barajas, Casco Histórico de Barajas', 'Pacífico, Pacífico',
       'Ríos Rosas, Ríos Rosas', 'Entrevías, Entrevías',
       'Embajadores, Embajadores-Lavapiés', 'San Diego, Palomeras Bajas',
       'Hispanoamérica, Hispanoamérica', 'Cortes, Cortes-Huertas',
       'Universidad, Universidad-Malasaña',
       'San Cristobal, San Cristóbal', 'Opañel, Opañel',
       'Las Águilas, Las Águilas', 'Moscardó, Moscardó',
       'Argüelles, Argüelles', 'El Viso, Almenara', 'Timón, Timón',
       'Pacífico, Casco Histórico de Vallecas', 'Goya, Recoletos',
       'Justicia, Justicia-Chueca', 'Pueblo Nuevo, Castilla',
       'Jerónimos, Moscardó', 'Pilar, Fuentelarreina',
       'Jerónimos, Comillas', 'Peñagrande, Peñagrande',
       'Virgen del Cortijo, Virgen del Cortijo-Manoteras',
       'San Fermín, San Fermín', 'Nueva España, Nueva España',
       'Miguel Hernandez, Orcasur', 'Trafalgar, Justicia-Chueca',
       'Valdecarros, Ensanche de Vallecas-Valdecarros',
       'Ciudad Jardín, Almagro', 'Jerónimos, Puerta Bonita',
       'Salamanca, Gaztambide', 'Zofio, Zofío', 'Fontarrón, Fontarrón',
       'Miguel Hernandez, San Diego', 'Ciudad Jardín, Ciudad Jardín',
       'Mirasierra, Mirasierra-Arroyo del Fresno',
       'Castellana, Valderrivas', 'Niño Jesús, Niño Jesús',
       'Castillejos, Peñagrande', 'Universidad', 'Latina',
       'Jerónimos, San Isidro', 'Trafalgar, Bellas Vistas',
       'Apóstol Santiago, Apóstol Santiago',
       'Carabanchel, Pau de Carabanchel', 'Recoletos, Comillas',
       'Recoletos, Palacio', 'Buenavista, Pau de Carabanchel',
       'Ventas, Fuente del Berro',
       'El Cañaveral - Los Berrocales, El Cañaveral',
       'Jerónimos, Casa de Campo', 'Jerónimos, Orcasur',
       'Recoletos, Cármenes', 'Rosas, Pueblo Nuevo', 'Zofio',
       'Valdebebas, Valdebebas-Valdefuentes', 'Miguel Hernandez',
       'Chamberí', 'Arganzuela', 'Valdebebas, VALDEBEBAS UNICO',
       'Rosas, Palomas', 'San Juan', 'Chamartín', 'Carabanchel',
       'Villa de Vallecas', 'La Paz, Calle Julio Palacios 29-31',
       'Vicálvaro', 'Puente de Vallecas', 'Jerónimos, Primitiva Gañan',
       'Valdefuentes', 'San Diego, Collado De Las Vertientes',
       'Salamanca', 'Jerónimos, Cármenes', 'Tetuán', 'Justicia',
       'Jerónimos, Padre Amigo', 'San Juán Bautista',
       'Miguel Hernandez, Gonzalez Soto', 'Castillejos, Molina',
       'Ensanche de Vallecas', 'Palomeras Bajas, Hispanoamérica',
       'El Plantío, El Plantío', 'Los Cármenes, Los Cármenes',
       'Jerónimos, Jerónimos', 'Cortes',
       'Santa Eugenia, Casco Histórico de Vallecas', 'Hellín, Hellín',
       'Valdemarín, Valdemarín', 'Jerónimos, Buenavista', 'San Blas',
       'Ciudad Jardín, Chopera', 'Chamberí, Recoletos', 'Hortaleza',
       'Retiro', 'Valdecarros', 'Horcajo, Estrella',
       'Trafalgar, Berruguete', 'Villaverde', 'Casco Histórico Vicálvaro',
       'Valderribas', 'Concepción, Urbanizacion Guadalupe',
       'Miguel Hernandez, Palomeras Bajas', 'Jerónimos, Imperial',
       'Puerta de Hierro', 'Mirasierra', 'Carabanchel, Pilar',
       'Trafalgar, Embajadores-Lavapiés', 'El Goloso', 'Usera',
       'Salamanca, Arapiles', 'Trafalgar, Cortes-Huertas', 'Madrid-Sur',
       'Trafalgar, Recoletos', 'Zona Industrial Vicálvaro, El Cañaveral',
       'Barrio del Pilar', 'Pacífico, Los Berrocales',
       'El Goloso, Mirasierra-Arroyo del Fresno', 'Arganzuela, Madrid',
       'Carabanchel, Numancia', 'Barajas, Los Coronales',
       'Horcajo, Ventas', 'Jerónimos, Pacífico', 'Palomas, Piovera',
       'El Viso, Valverde', 'Salamanca, Magán',
       'Cuatro Caminos, Almenara', 'El Goloso, El Pardo',
       'Chamberí, Castellana', 'Cortes, Ensanche de Vallecas-La Gavia',
       'Valdemarín, Ciudad Universitaria', 'Valdeacederas, SORGO 14',
       'Arturo Soria', 'Horcajo', 'Arganzuela, JUNTO PUERTA DE TOLEDO',
       'Palomas, Palomeras Bajas', 'San Juán Bautista, San Juan Bautista',
       'Valdefuentes, Valdebebas-Valdefuentes', 'San Cristobal',
       'Hortaleza, Ensanche', 'Jerónimos, Tranquilo',
       'Carabanchel, Castilla', 'Salamanca, Universidad-Malasaña',
       'El Goloso, Madrid ,Fuencarral',
       'Justicia, Bueno y tranquilo. Agua incl. en comunidad.',
       'Comillas, Carabanchel', 'Chamberí, Niño Jesús', 'Los Cármenes',
       'Nueva Numancia, AMUEBLADO   CON TRASTERO INCLUIDO PARA ENTRAR EN VIVIR',
       'Recoletos, Arapiles', 'Goya, Atocha', 'San Diego, Adelfas',
       'El Viso, Almagro', 'Trafalgar, Gaztambide',
       'Recoletos, Nueva España', 'Recoletos, Aluche',
       'Acacias, Imperial', 'Recoletos, San Isidro',
       'El Cañaveral - Los Berrocales', 'Casco Histórico de Vicálvaro',
       'Piovera-Conde de Orgaz', 'Buena Vista', 'Valdefuentes-Valdebebas',
       'Ensanche de Vallecas-La Gavia',
       'Corralejos-Campo de las Naciones', 'Hispanoamérica-Bernabéu',
       'Orcasur-12 de Octubre', 'Ventas, Atalaya', 'Goya, Delicias',
       'Goya, San Pascual', 'Almenara-Ventilla',
       'Valdebernardo-Valderribas', 'Nueva Numancia', 'Chamberí, Arcos',
       'Pacífico, Ambroz', 'El Cañaveral-Los Berrocales',
       'Jerónimos, Fuente del Berro', 'San Andrés, San Fermín',
       'Castellana, Arcos', 'Alto del Arenal', 'San Isidro, xxxx',
       'San Pascual, Esquina a calle Torrelaguna',
       'Arapiles, Conde Duque-San Bernardo',
       'Los Ángeles, colonia del ahorro', 'Arroyo del Fresno',
       'Jerónimos, Abrantes', 'Trafalgar, Almagro',
       'Jerónimos, Las Águilas', 'Pacífico, Hellín',
       'Recoletos, Estrella', 'Covibar-Pablo Iglesias', 'Jerónimos, Sol',
       'Buenavista, Cuatro Vientos', 'El Viso, Cuatro Caminos',
       'Universidad, Sol', 'Jerónimos, Acacias', 'Embajadores, Delicias',
       'Tetuán, Madrid', 'Ciudad Jardín, Lista', 'Gaztambide, Galaxia',
       'Valdemarín, Casa Quemada', 'Valdebebas',
       'Aeropuerto, Urb. Mas Nou', 'Palomas, Rejas',
       'Valdebebas, URBANIZACION VALDEBEBAS',
       'Cuatro Caminos, Apóstol Santiago', 'Nueva España, Plaza de cuzco',
       'Castellana, Rosas', 'Canillejas, COLONIA ALFONSOXII',
       'Valdezarza, DEHESA DE LA VILLA PUERTA DE HIERRO',
       'Montecillo-Pinar de las Rozas', 'Concepción, Hispanoamérica',
       'Latina, ECUADOR -MITAD DEL  MUNDO - ECUADOR -  SURAMERICA',
       'Trafalgar, Valdemarín', 'Estremera', 'El Viso, Chamartín'],
      dtype=object)

In [6]:
unique_locs = df_filtered['loc'].unique()
len(unique_locs)

366

In [7]:
loc_f = df_filtered.apply(lambda row:row['loc'].split(',')[0], axis = 1)
loc_f = loc_f.apply(lambda row:row.split(' - ')[0])

In [8]:
# Replacing filtered location column
df_filtered = df_filtered.assign(loc=loc_f)

### Identifying district names

In [9]:
with open('districts', 'r') as file:
    data = file.read()

stub_0 = data.split('\n\n')

# Creating a district map of the form: {district_a -> wards_in_district_a*}
dt_map = {}
for dist_0 in stub_0:
    split_0 = dist_0.split('\n')
    dt_map[split_0[0]] = split_0[1:]

In [10]:
print(dt_map)

{'Centro': ['Palacio', 'Embajadores', 'Cortes', 'Justicia', 'Universidad', 'Sol'], 'Arganzuela': ['Imperial', 'Acacias', 'Chopera', 'Legazpi', 'Delicias', 'Palos de Moguer', 'Atocha'], 'Retiro': ['Pacífico', 'Adelfas', 'Estrella', 'Ibiza', 'Jerónimos', 'Niño Jesús'], 'Salamanca': ['Recoletos', 'Goya', 'Fuente del Berro', 'Guindalera', 'Lista', 'Castellana'], 'Chamartín': ['El Viso', 'Prosperidad', 'Ciudad Jardín', 'Hispanoamérica', 'Nueva España', 'Castilla'], 'Tetuán': ['Bellas Vistas', 'Cuatro Caminos', 'Castillejos', 'Almenara', 'Valdeacederas', 'Berruguete'], 'Chamberí': ['Gaztambide', 'Arapiles', 'Trafalgar', 'Almagro', 'Ríos Rosas', 'Vallehermoso'], 'Fuencarral-El Pardo': ['El Pardo', 'Fuentelarreina', 'Peñagrande', 'Pilar', 'La Paz', 'Valverde', 'Mirasierra', 'El Goloso'], 'Moncloa-Aravaca': ['Casa de Campo', 'Argüelles', 'Ciudad Universitaria', 'Valdezarza', 'Valdemarín', 'El Plantío', 'Aravaca'], 'Latina': ['Los Cármenes', 'Puerta del Ángel', 'Lucero', 'Aluche', 'Campamento', 'Cuatro Vientos', 'Las Águilas'], 'Carabanchel': ['Comillas', 'Opañel', 'San Isidro', 'Vista Alegre', 'Puerta Bonita', 'Buenavista', 'Abrantes'], 'Usera': ['Orcasitas', 'Orcasur', 'San Fermín', 'Almendrales', 'Moscardó', 'Zofío', 'Pradolongo'], 'Puente de Vallecas': ['Entrevías', 'San Diego', 'Palomeras Bajas', 'Palomeras Sureste', 'Portazgo', 'Numancia'], 'Moratalaz': ['Pavones', 'Horcajo', 'Marroquina', 'Media Legua', 'Fontarrón', 'Vinateros'], 'Ciudad Lineal': ['Ventas', 'Pueblo Nuevo', 'Quintana', 'Concepción', 'San Pascual', 'San Juan Bautista', 'Colina', 'Atalaya', 'Costillares'], 'Hortaleza': ['Palomas', 'Piovera', 'Canillas', 'Pinar del Rey', 'Apóstol Santiago', 'Valdefuentes'], 'Villaverde': ['Villaverde Alto', 'San Cristóbal', 'Butarque', 'Los Rosales', 'Los Ángeles'], 'Villa de Vallecas': ['Casco Histórico de Vallecas', 'Santa Eugenia', 'Ensanche de Vallecas'], 'Vicálvaro': ['Casco Histórico de Vicálvaro', 'Valdebernardo', 'Valderrivas', 'El Cañaveral'], 'San Blas-Canillejas': ['Simancas', 'Hellín', 'Amposta', 'Arcos', 'Rosas', 'Rejas', 'Canillejas', 'Salvador'], 'Barajas': ['Alameda de Osuna', 'Aeropuerto', 'Casco Histórico de Barajas', 'Timón', 'Corralejos']}

In [11]:
# Replacing each location with its district name (if possible)
def find_dt(loc):
    for dt,wards in dt_map.items():
        if (loc == dt):
            return loc
        elif (loc in wards):
            return dt
    return None

# Replacing location column with district names
loc_f = df_filtered.apply(lambda row:find_dt(row['loc']), axis = 1)
df_filtered = df_filtered.assign(loc=loc_f)

In [12]:
display(df_filtered)

,url,address,loc,price,m2,type
0,https://pisos.com/en/comprar/casa-puente_de_va...,"calle de mejorana, near calle del conde rodríg...",Puente de Vallecas,128000,76.0,house
1,https://pisos.com/en/comprar/chalet_adosado-ch...,hispanoamerica,Chamartín,990000,287.0,house
2,https://pisos.com/en/comprar/chalet-nino_jesus...,niño jesús,Retiro,1318000,263.0,house
3,https://pisos.com/en/comprar/chalet-puente_de_...,"calle de membezar, near calle de la campiña",Puente de Vallecas,139000,69.0,house
4,https://pisos.com/en/comprar/chalet-chamartin_...,chamartin,Chamartín,1390000,370.0,house
...,...,...,...,...,...,...
30060,http://english.habitaclia.com/buy-house-cerro_...,NaN,None,345000,200.0,house
30061,http://english.habitaclia.com/buy-semi_detache...,NaN,Carabanchel,450000,250.0,house
30062,http://english.habitaclia.com/buy-semi_detache...,NaN,Puente de Vallecas,89000,38.0,house
30063,http://english.habitaclia.com/buy-semi_detache...,NaN,San Blas-Canillejas,670000,340.0,house
30064,http://english.habitaclia.com/buy-house-penagr...,NaN,Fuencarral-El Pardo,1250000,519.0,house

In [13]:
# Removing rows with unidentified districts
df_filtered = df_filtered.dropna(subset=['loc']).reset_index(drop=True)

### Computing price/m2 for every entry

In [14]:
# Extracting columns
df_final = df_filtered[['loc', 'price', 'm2']]

# Converting data types
num_price = pd.to_numeric(df_final['price'], errors='coerce')
num_m2 =pd.to_numeric(df_final['m2'], errors='coerce')

df_final = df_final.assign(m2=num_m2,price=num_price)
df_final = df_final.dropna(subset=['price', 'm2']).reset_index(drop=True)
display(df_final)

                       loc      price     m2
0       Puente de Vallecas   128000.0   76.0
1                Chamartín   990000.0  287.0
2                   Retiro  1318000.0  263.0
3       Puente de Vallecas   139000.0   69.0
4                Chamartín  1390000.0  370.0
...                    ...        ...    ...
25057            Chamartín  6000000.0  670.0
25058          Carabanchel   450000.0  250.0
25059   Puente de Vallecas    89000.0   38.0
25060  San Blas-Canillejas   670000.0  340.0
25061  Fuencarral-El Pardo  1250000.0  519.0

[25062 rows x 3 columns]

In [15]:
df_final['m2price'] = df_final.apply(lambda row: row['price']/row['m2'], axis=1)

In [16]:
display(df_final)

                       loc      price     m2      m2price
0       Puente de Vallecas   128000.0   76.0  1684.210526
1                Chamartín   990000.0  287.0  3449.477352
2                   Retiro  1318000.0  263.0  5011.406844
3       Puente de Vallecas   139000.0   69.0  2014.492754
4                Chamartín  1390000.0  370.0  3756.756757
...                    ...        ...    ...          ...
25057            Chamartín  6000000.0  670.0  8955.223881
25058          Carabanchel   450000.0  250.0  1800.000000
25059   Puente de Vallecas    89000.0   38.0  2342.105263
25060  San Blas-Canillejas   670000.0  340.0  1970.588235
25061  Fuencarral-El Pardo  1250000.0  519.0  2408.477842

[25062 rows x 4 columns]

In [42]:
# Selecting only localization and €/m2
df_result = df_final[['loc', 'm2price']]

# Computing means with confidence interval
m2p_dt = df_result.groupby(['loc'])['m2price'].apply(list).to_dict()

def print_avg(name, seq):
    # Computing average with 0.95 error margin (rounded to 2 decimal places)
    ic = st.t.interval(0.95, len(seq)-1, loc=np.mean(seq), scale=st.sem(seq))
    print(name, round(np.mean(seq),2), "+-" + str(round((ic[1] - ic[0])/2,2)))    

for dt,m2p in m2p_dt.items():
    # Rejecting outlier values
    m2p = np.array(m2p)
    m2p = m2p[abs(m2p - np.mean(m2p)) < 2*np.std(m2p)]
    
    print_avg(dt, m2p)

Arganzuela 3994.92 +-49.5
Barajas 3067.08 +-70.91
Carabanchel 2219.89 +-27.01
Centro 4948.7 +-66.58
Chamartín 5391.62 +-77.38
Chamberí 5409.88 +-67.29
Ciudad Lineal 3168.79 +-40.04
Fuencarral-El Pardo 3360.4 +-55.66
Hortaleza 3394.89 +-63.0
Latina 2394.98 +-35.47
Moncloa-Aravaca 7615.72 +-3414.71
Moratalaz 2590.58 +-45.98
Puente de Vallecas 1981.02 +-20.56
Retiro 4524.09 +-83.79
Salamanca 5944.73 +-72.47
San Blas-Canillejas 2611.05 +-36.81
Tetuán 3598.43 +-53.02
Usera 2046.5 +-34.94
Vicálvaro 2247.72 +-54.01
Villa de Vallecas 2068.14 +-49.57
Villaverde 1767.97 +-28.42

In [46]:
# Computing global average and margin of error
all_m2p = df_final['m2price']
all_m2p = np.array(all_m2p)
all_m2p = all_m2p[abs(all_m2p - np.mean(all_m2p)) < 2*np.std(all_m2p)]
print_avg("All districts", all_m2p)

All districts 3818.42 +-24.8